// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import ()

type ChatMessage struct {
	ID         int64  `json:"id"`
	Content    string `json:"content"`
	SentBySelf bool   `json:"sentBySelf"`
}
