// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"time"
)

type Conversation struct {
	ID              int       `json:"id"`
	Title           string    `json:"title"`
	LastMessageTime time.Time `json:"lastMessageTime"`
	Generating      bool      `json:"generating"`
	SystemPrompt    string    `json:"systemPrompt"`
}

type Message struct {
	ID             int    `json:"id"`
	ConversationID int    `json:"conversationID"`
	Content        string `json:"content"`
	Author         string `json:"author"`
}
