// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelGeneration(arg1) {
  return window['go']['main']['App']['CancelGeneration'](arg1);
}

export function Conversations() {
  return window['go']['main']['App']['Conversations']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversationSettings(arg1) {
  return window['go']['main']['App']['GetConversationSettings'](arg1);
}

export function GetDefaultConversationSettings() {
  return window['go']['main']['App']['GetDefaultConversationSettings']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Messages(arg1) {
  return window['go']['main']['App']['Messages'](arg1);
}

export function RerunFromMessage(arg1, arg2) {
  return window['go']['main']['App']['RerunFromMessage'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetDefaultConversationSettings(arg1) {
  return window['go']['main']['App']['SetDefaultConversationSettings'](arg1);
}

export function UpdateConversationSettings(arg1) {
  return window['go']['main']['App']['UpdateConversationSettings'](arg1);
}
