// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';

export function CancelGeneration(arg1:number):Promise<void>;

export function Conversations():Promise<Array<database.Conversation>>;

export function DeleteConversation(arg1:number):Promise<void>;

export function GetAvailableTools():Promise<Array<main.AvailableTool>>;

export function GetConversation(arg1:number):Promise<database.Conversation>;

export function GetConversationSettings(arg1:number):Promise<database.ConversationSetting>;

export function GetDefaultConversationSettings():Promise<database.ConversationSetting>;

export function GetSettings():Promise<database.Settings>;

export function Messages(arg1:number):Promise<Array<database.Message>>;

export function RerunFromMessage(arg1:number,arg2:number):Promise<void>;

export function SaveSettings(arg1:database.Settings):Promise<void>;

export function SendMessage(arg1:number,arg2:string):Promise<database.Message>;

export function SetDefaultConversationSettings(arg1:database.CreateDefaultConversationSettingsParams):Promise<database.ConversationSetting>;

export function UpdateConversationSettings(arg1:database.UpdateConversationSettingsParams):Promise<database.ConversationSetting>;
